In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [2]:
from sklearn.metrics import balanced_accuracy_score, confusion_matrix
from imblearn.metrics import classification_report_imbalanced

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)

In [3]:
from google.colab import files
uploaded = files.upload()

Saving cases_by_status_and_phu.csv to cases_by_status_and_phu (3).csv

In [4]:
file_path = Path('cases_by_status_and_phu.csv')
cases_df = pd.read_csv(file_path)
cases_df.head()

    FILE_DATE                                 PHU_NAME  ...  RESOLVED_CASES  DEATHS
0  2020-04-10         HALIBURTON, KAWARTHA, PINE RIDGE  ...              69      18
1  2020-04-10                            HALTON REGION  ...             137       9
2  2020-04-10        HASTINGS & PRINCE EDWARD COUNTIES  ...              11       1
3  2020-04-10                              HURON PERTH  ...               8       1
4  2020-04-10  KINGSTON, FRONTENAC, LENNOX & ADDINGTON  ...              39       0

[5 rows x 6 columns]

In [5]:
cases_df.dropna()

        FILE_DATE  ... DEATHS
0      2020-04-10  ...     18
1      2020-04-10  ...      9
2      2020-04-10  ...      1
3      2020-04-10  ...      1
4      2020-04-10  ...      0
...           ...  ...    ...
14071  2021-05-13  ...   3194
14072  2021-05-13  ...    254
14073  2021-05-13  ...    110
14074  2021-05-13  ...    423
14075  2021-05-13  ...    693

[14075 rows x 6 columns]

In [6]:
cases_df['FILE_DATE'] = pd.to_datetime(cases_df['FILE_DATE'], errors='coerce')

In [7]:
cases_df['WEEK'] = cases_df['FILE_DATE'].dt.week
cases_df['MONTH'] = cases_df['FILE_DATE'].dt.month
cases_df['YEAR'] = cases_df['FILE_DATE'].dt.year
cases_df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  """Entry point for launching an IPython kernel.

   FILE_DATE                                 PHU_NAME  ...  MONTH  YEAR
0 2020-04-10         HALIBURTON, KAWARTHA, PINE RIDGE  ...      4  2020
1 2020-04-10                            HALTON REGION  ...      4  2020
2 2020-04-10        HASTINGS & PRINCE EDWARD COUNTIES  ...      4  2020
3 2020-04-10                              HURON PERTH  ...      4  2020
4 2020-04-10  KINGSTON, FRONTENAC, LENNOX & ADDINGTON  ...      4  2020

[5 rows x 9 columns]

In [8]:
cases_df = cases_df.drop(columns=['FILE_DATE'])

In [32]:
weekly_cases_per_unit_df = cases_df.groupby(['PHU_NAME']).count()
weekly_cases_per_unit_df

                                         PHU_NUM  ACTIVE_CASES  ...  MONTH  YEAR
PHU_NAME                                                        ...
ALGOMA DISTRICT                              414           414  ...    414   414
BRANT COUNTY                                 414           414  ...    414   414
CHATHAM-KENT                                 414           414  ...    414   414
CITY OF HAMILTON                             414           414  ...    414   414
CITY OF OTTAWA                               414           414  ...    414   414
DURHAM REGION                                414           414  ...    414   414
EASTERN ONTARIO                              414           414  ...    414   414
GREY BRUCE                                   414           414  ...    414   414
HALDIMAND-NORFOLK                            414           414  ...    414   414
HALIBURTON, KAWARTHA, PINE RIDGE             414           414  ...    414   414
HALTON REGION                                414           414  ...    414   414
HASTINGS & PRINCE EDWARD COUNTIES            414           414  ...    414   414
HURON PERTH                                  413           413  ...    413   413
KINGSTON, FRONTENAC, LENNOX & ADDINGTON      414           414  ...    414   414
LAMBTON COUNTY                               414           414  ...    414   414
LEEDS, GRENVILLE AND LANARK DISTRICT         414           414  ...    414   414
MIDDLESEX-LONDON                             414           414  ...    414   414
NIAGARA REGION                               414           414  ...    414   414
NORTH BAY PARRY SOUND DISTRICT               414           414  ...    414   414
NORTHWESTERN                                 414           414  ...    414   414
OXFORD ELGIN-ST.THOMAS                       414           414  ...    414   414
PEEL REGION                                  414           414  ...    414   414
PETERBOROUGH COUNTY-CITY                     414           414  ...    414   414
PORCUPINE                                    414           414  ...    414   414
RENFREW COUNTY AND DISTRICT                  414           414  ...    414   414
SIMCOE MUSKOKA DISTRICT                      414           414  ...    414   414
SUDBURY AND DISTRICT                         414           414  ...    414   414
THUNDER BAY DISTRICT                         414           414  ...    414   414
TIMISKAMING                                  414           414  ...    414   414
TORONTO                                      414           414  ...    414   414
WATERLOO REGION                              414           414  ...    414   414
WELLINGTON-DUFFERIN-GUELPH                   414           414  ...    414   414
WINDSOR-ESSEX COUNTY                         414           414  ...    414   414
YORK REGION                                  414           414  ...    414   414

[34 rows x 7 columns]

In [ ]:
uploaded = files.upload()

In [ ]:
file2_path = Path('Ministry_of_Health_Public_Health_Unit_Boundary.csv')
boundary_df = pd.read_csv(file2_path)
boundary_df.head()

In [ ]:
boundary_df.dropna()

In [ ]:
boundary_df.drop(columns=['NAME_FR', 'GEO_UPD_DT'])